global:
  scrape_interval: 15s # 15초마다 데이터 수집

scrape_configs:
  - job_name: 'todo-tracker'
    metrics_path: '/actuator/prometheus' # 데이터 가져올 경로
    static_configs:
      # localhost는 도커 컨테이너 내부에서 호스트(내 컴퓨터)를 가리키는 주소
      # 도커 컨테이너에서 내 컴퓨터(Host)의 8080포트를 찾으려면 host.docker.internal을 사용해야 함
      - targets: ['host.docker.internal:8080']